# Testing
# This is a basic workflow to help you get started with Actions

name: EC2-on-demand
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [on-demand-ec2-test]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Configure AWS credentials
        #uses: aws-actions/configure-aws-credentials@v1
        #with:
        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  aws-region: central
      #- name: Start EC2 runner
        #id: start-ec2-runner
        #uses: ubc-tuehoang/ec2-github-runner@v1
        #with:
        #  mode: start
        #  github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        #  ec2-image-id: ami-0cc7eea4d616ff
        #  ec2-instance-type: t2.micro
        #  subnet-id: subnet-00d1cc7b
        #  security-group-id: tue-security-group
        #  iam-role-name: my-role-name # optional, requires additional permissions
        #  aws-resource-tags: > # optional, requires additional permissions
        #    [
        #      {"Key": "Name", "Value": "ec2-github-runner"},
        #      {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
        #    ]
        #EC2-on-demand:
        #  name: Launch EC2-on-demand
        #  needs: start-runner # required to start the main job when the runner is ready
        #  runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
        #  steps:
        #    - name: Whatever
        #      run: echo 'Whatever EC2'
        #stop-runner:
        #  name: Stop self-hosted EC2 runner
        #  needs:
        #    - start-runner # required to get output from the start-runner job
        #    - EC2-on-demand # required to wait when the main job is done
        #  runs-on: ubuntu-latest
        #  if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
        #  steps:
        #    - name: Configure AWS credentials
        #      uses: aws-actions/configure-aws-credentials@v1
        #      with:
        #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #        aws-region: central
        #    - name: Stop EC2 runner
        #      uses: ubc-tuehoang/ec2-github-runner@v1
        #      with:
        #        mode: stop
        #        github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        #        label: ${{ needs.start-runner.outputs.label }}
        #        ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: WP
        name: WP
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          pwd
          ls
          echo "Level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        shell: bash 

 # Add new files in folder, commit along with other modified files, push

